### ISSUE TITLE
over-eager syntax error reporting for break and continue

### ISSUE THREAD

**Issue by jpolitz** [brownplt/lambda-py#56]
Just pushed two tests in 95dad02d1cc4255dbfda3f8e7008cfc794062084 that show we're over-zealously checking for break and continue in the wrong places.

Can we just use Python's compile() in parse-python.py, catch errors from the parse in Racket, and produce the thrown syntax error there?  It seems like we're reproducing a lot of effort that Python has already put in for us, and getting it wrong.

**Comment by mpmilano** [comment]
We absolutely could.  Sorry for the wasted effort; I managed to remain
oblivious to the compile() function.  Hooking it in now.

**Comment by mpmilano** [comment]
The compile() function is now how we determine SyntaxErrors; the
process-syntax-errors pass is now a noop.

Additionally, the default target in the makefile now will warn you if you
have files with non-ascii characters in them.  I managed to lose two hours
due to one of these; hopefully the warning will help us avoid them in the
future.  It only checks base/, not the tests.

~matthew

**Comment by jpolitz** [comment]
Shoot!  I saw that and forgot to push the fix.  object's with a non-ascii
unicode apostrophe again.

**Comment by mpmilano** [comment]
fixed in 709ab5742ea45d850542ba94857ca7827b6c7626
